name: Authed
main: cc.co.vijfhoek.authed.Authed
version: 0.3.1
commands:
  login:
    description: Log into your account
    usage: /login <password>
  register:
    description: Register your name
    usage: /register <password>